/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javainventorypos;

import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class insertInv extends javax.swing.JFrame {

    Connection con = null;
    Statement stmt = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form insertInv
     */
    public insertInv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pqty = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pprice = new javax.swing.JTextField();
        sbutton = new javax.swing.JButton();
        bbutton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Product Code");

        jLabel2.setText("Product Name");

        jLabel3.setText("Quantity");

        jLabel4.setText("Selling Price");

        sbutton.setText("Submit");
        sbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbuttonActionPerformed(evt);
            }
        });

        bbutton.setText("Back");
        bbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbuttonActionPerformed(evt);
            }
        });

        jLabel5.setText("Date (YYYY-MM-DD)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pdate)
                    .addComponent(pname)
                    .addComponent(pcode)
                    .addComponent(pqty)
                    .addComponent(pprice)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addComponent(sbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbutton)
                    .addComponent(sbutton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public static boolean isNumeric(String str){
        try{  
          double d = Double.parseDouble(str);  
        }  
        catch(NumberFormatException nfe){  
          return false;  
        }  
        return true;  
    }
    
    public static boolean isValidDate(String inDate) {
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    dateFormat.setLenient(false);
    try {
      dateFormat.parse(inDate.trim());
    } catch (ParseException pe) {
      return false;
    }
    return true;
  }
    
    
    private void clearTF(){
        pcode.setText("");
        pname.setText("");
        pqty.setText("");
        pprice.setText("");
//        pdate.setText("");
    }
    
    private boolean checkDupe(){
        int dupe = 0;
        
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/inventory","root","");

                String prodcode = (String) pcode.getText();

                String sql = "SELECT * FROM transactions WHERE prodcode='"+prodcode+"'";
                stmt = con.createStatement();
                rs = stmt.executeQuery(sql);

                while (rs.next()) {
                    dupe = dupe+1;
                }
            
        }
        catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);  
        }
        
        if (dupe >= 1){ //there is dupe product
                    return true;
                }
                else{
                    return false;
                }
    }
    
    private void addTrans(){
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/inventory","root","");

            
//                LocalDate transdate = LocalDate.now(ZoneId.of( "Asia/Shanghai" ));
                String sql = "INSERT INTO transactions(prodcode,prodname,qty,price,transdate,tinout) VALUES(?,?,?,?,?,?)";
                pst = con.prepareStatement(sql);

                String prodcode = (String) pcode.getText();
                String prodname = (String) pname.getText();
                String qty = (String) pqty.getText();
                String price = (String) pprice.getText();
                String transdate = (String) pdate.getText();
                java.sql.Date sqlDate = java.sql.Date.valueOf(transdate);
                String tinout = "IN";

                pst.setString(1,prodcode);
                pst.setString(2,prodname);
                pst.setString(3,qty);
                pst.setString(4,price);
                pst.setDate(5,sqlDate);
                pst.setString(6,tinout);
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Transaction Recorded Successfully.");
            
        }
        catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);  
        }
    }
    
    private void submitdb(){
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/inventory","root","");

            
                String sql = "INSERT INTO inv(prodcode,prodname,stock,price) VALUES(?,?,?,?)";
                pst = con.prepareStatement(sql);

                String prodcode = (String) pcode.getText();
                String prodname = (String) pname.getText();
                String qty = (String) pqty.getText();
                String price = (String) pprice.getText();

                pst.setString(1,prodcode);
                pst.setString(2,prodname);
                pst.setString(3,qty);
                pst.setString(4,price);
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Product Inserted Successfully.");
            
        }
        catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);  
        }
    }
    
    private void updatedb(){
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/inventory","root","");

            
                String sql = "UPDATE inv SET stock=stock+? WHERE prodcode=?";
                pst = con.prepareStatement(sql);
                String stock = (String) pqty.getText();
                String prodcode = (String) pcode.getText();
                pst.setString(1,stock);
                pst.setString(2,prodcode);
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Duplicate Product, Stocks Updated Successfully.");
            
        }
        catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);  
        }
        
    }
    
    private void sbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbuttonActionPerformed
        // TODO add your handling code here:
        if (pcode.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please input Product Code.");
                }
        else if (pname.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please input Product Name.");
                }
        else if (isNumeric((String) pqty.getText()) == false){
                JOptionPane.showMessageDialog(null, "Quantity must be a number.");
                }
        else if (isNumeric((String) pprice.getText()) == false){
                JOptionPane.showMessageDialog(null, "Price must be a number.");
                }
        else if (isValidDate((String) pdate.getText()) == false){
                JOptionPane.showMessageDialog(null, "Date must be in YYYY-MM-DD format.");
                }
        else{
            if (checkDupe() == false){ // no dupes
                submitdb();
                addTrans();
                clearTF();
            }
            else{ //dupes
                updatedb();
                addTrans();
                clearTF();
            }
        }
    }//GEN-LAST:event_sbuttonActionPerformed

    private void bbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbuttonActionPerformed
        // TODO add your handling code here:  
        new mainInv().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(insertInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(insertInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(insertInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(insertInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insertInv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pcode;
    private javax.swing.JTextField pdate;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pprice;
    private javax.swing.JTextField pqty;
    private javax.swing.JButton sbutton;
    // End of variables declaration//GEN-END:variables
}
